spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

services:
  product:
    url: http://product-service:8080
  payment:
    url: http://payment-service:8080

logging:
  level:
    root: INFO
    com.example: DEBUG
    io.opentelemetry: INFO
